/** EastAfricaExplore — public site, enquiries, and secure lightweight CMS. */
const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const ROOT=__dirname,PORT=Number(process.env.PORT)||3000,COOKIE_SECURE=process.env.COOKIE_SECURE==="true",DATA=path.join(ROOT,"data"),CATALOG=path.join(DATA,"catalog.json"),ADMIN=path.join(DATA,"admin.json"),ENQUIRIES=path.join(DATA,"enquiries.json"),LEGACY_ENQUIRIES=path.join(DATA,"enquiries.jsonl"),BOOKINGS=path.join(DATA,"bookings.json"),CLICKS=path.join(DATA,"affiliate-clicks.jsonl");
const MIME={".html":"text/html; charset=utf-8",".js":"text/javascript; charset=utf-8",".css":"text/css; charset=utf-8",".png":"image/png",".jpg":"image/jpeg",".jpeg":"image/jpeg",".webp":"image/webp",".avif":"image/avif",".svg":"image/svg+xml",".json":"application/json; charset=utf-8"};
const sessions=new Map();
const clean=(v,n=500)=>String(v??"").trim().slice(0,n),email=v=>/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/.test(v);
function json(res,status,body,extra={}){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Cache-Control":"no-store","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin",...extra});res.end(JSON.stringify(body));}
function body(req){return new Promise((ok,no)=>{let b="";req.on("data",c=>{b+=c;if(b.length>1e6)no(Error("Request too large"));});req.on("end",()=>{try{ok(JSON.parse(b||"{}"));}catch{no(Error("Invalid JSON"));}});req.on("error",no);});}
function cookies(req){return Object.fromEntries((req.headers.cookie||"").split(";").filter(Boolean).map(v=>{const i=v.indexOf("=");return[decodeURIComponent(v.slice(0,i).trim()),decodeURIComponent(v.slice(i+1))]}));}
function session(req){const s=sessions.get(cookies(req).eae_session);if(!s||s.expires<Date.now())return null;s.expires=Date.now()+8*60*60*1000;return s;}
function hashPassword(password,salt=crypto.randomBytes(16).toString("hex")){return{salt,hash:crypto.scryptSync(password,salt,64).toString("hex")};}
function verifyPassword(password,record){const candidate=crypto.scryptSync(password,record.salt,64),stored=Buffer.from(record.hash,"hex");return stored.length===candidate.length&&crypto.timingSafeEqual(stored,candidate);}
function readJSON(file,fallback){try{return JSON.parse(fs.readFileSync(file,"utf8"));}catch{return fallback;}}
function writeJSON(file,value){fs.mkdirSync(DATA,{recursive:true});const temp=`${file}.${process.pid}.tmp`;fs.writeFileSync(temp,JSON.stringify(value,null,2));fs.renameSync(temp,file);}
function safeItem(x,type){
  const item={id:clean(x.id,80)||crypto.randomUUID(),type,title:clean(x.title,100),location:clean(x.location,100),country:clean(x.country,60),description:clean(x.description,1500),summary:clean(x.summary,350),image:clean(x.image,240),gallery:Array.isArray(x.gallery)?x.gallery.slice(0,8).map(v=>clean(v,240)):[],price:Math.max(0,Number(x.price)||0),currency:clean(x.currency,6)||"USD",rating:Math.min(5,Math.max(0,Number(x.rating)||0)),features:Array.isArray(x.features)?x.features.slice(0,12).map(v=>clean(v,100)):[],includes:Array.isArray(x.includes)?x.includes.slice(0,12).map(v=>clean(v,100)):[],tags:Array.isArray(x.tags)?x.tags.slice(0,10).map(v=>clean(v,40)):[],duration:clean(x.duration,60),affiliateUrl:clean(x.affiliateUrl,500),published:x.published!==false,featured:Boolean(x.featured),updatedAt:new Date().toISOString()};
  if(!item.title||!item.location||!item.image)throw Error("Title, location and image are required.");
  if(item.affiliateUrl){const u=new URL(item.affiliateUrl);if(u.protocol!=="https:"||!/(^|\.)booking\.com$/i.test(u.hostname))throw Error("Affiliate link must be an HTTPS booking.com URL.");}
  return item;
}
function publicCatalog(){const c=readJSON(CATALOG,{destinations:[],hotels:[],safaris:[]});return{destinations:(c.destinations||[]).filter(x=>x.published!==false),hotels:(c.hotels||[]).filter(x=>x.published!==false),safaris:(c.safaris||[]).filter(x=>x.published!==false),managed:fs.existsSync(CATALOG)};}
function requireAdmin(req,res){const s=session(req);if(!s){json(res,401,{ok:false,error:"Please sign in."});return null;}return s;}
function adminWrite(req,res){const s=requireAdmin(req,res);if(!s)return null;if(req.headers["x-csrf-token"]!==s.csrf){json(res,403,{ok:false,error:"Your session could not be verified. Refresh and try again."});return null;}return s;}
function readEnquiries(){const current=readJSON(ENQUIRIES,null);if(Array.isArray(current))return current;try{const legacy=fs.readFileSync(LEGACY_ENQUIRIES,"utf8").split("\n").filter(Boolean).map(JSON.parse);writeJSON(ENQUIRIES,legacy);return legacy;}catch{return[];}}

const server=http.createServer(async(req,res)=>{const url=new URL(req.url,`http://${req.headers.host||"localhost"}`),p=url.pathname;
  if(p==="/api/health")return json(res,200,{ok:true,service:"eastafricaexplore",time:new Date().toISOString()});
  if(p==="/api/catalog"&&req.method==="GET")return json(res,200,publicCatalog());
  if(p==="/api/admin/status"&&req.method==="GET"){const s=session(req);return json(res,200,{configured:fs.existsSync(ADMIN),authenticated:Boolean(s),email:s?.email||null,csrf:s?.csrf||null});}
  if(p==="/api/admin/setup"&&req.method==="POST")try{if(fs.existsSync(ADMIN))return json(res,409,{ok:false,error:"Administrator setup is already complete."});const b=await body(req),mail=clean(b.email,120).toLowerCase(),password=String(b.password||"");if(!email(mail)||password.length<12)return json(res,400,{ok:false,error:"Use a valid email and a password of at least 12 characters."});writeJSON(ADMIN,{email:mail,...hashPassword(password),createdAt:new Date().toISOString()});return json(res,201,{ok:true});}catch(e){return json(res,400,{ok:false,error:e.message});}
  if(p==="/api/admin/login"&&req.method==="POST")try{const b=await body(req),a=readJSON(ADMIN,null);if(!a||clean(b.email,120).toLowerCase()!==a.email||!verifyPassword(String(b.password||""),a))return json(res,401,{ok:false,error:"Email or password is incorrect."});const id=crypto.randomBytes(32).toString("hex"),csrf=crypto.randomBytes(24).toString("hex");sessions.set(id,{email:a.email,csrf,expires:Date.now()+8*60*60*1000});return json(res,200,{ok:true,csrf},{"Set-Cookie":`eae_session=${id}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${COOKIE_SECURE?"; Secure":""}`});}catch{return json(res,400,{ok:false,error:"Could not sign in."});}
  if(p==="/api/admin/logout"&&req.method==="POST"){const id=cookies(req).eae_session;if(id)sessions.delete(id);return json(res,200,{ok:true},{"Set-Cookie":`eae_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0${COOKIE_SECURE?"; Secure":""}`});}
  if(p==="/api/admin/catalog"&&req.method==="GET"){if(!requireAdmin(req,res))return;return json(res,200,readJSON(CATALOG,{destinations:[],hotels:[],safaris:[]}));}
  if(p==="/api/admin/catalog"&&req.method==="PUT")try{const s=requireAdmin(req,res);if(!s)return;if(req.headers["x-csrf-token"]!==s.csrf)return json(res,403,{ok:false,error:"Your session could not be verified. Refresh and try again."});const b=await body(req);const destinations=(b.destinations||[]).map(x=>({id:clean(x.id,80)||crypto.randomUUID(),name:clean(x.name,80),country:clean(x.country,60),summary:clean(x.summary,300),image:clean(x.image,240),published:x.published!==false})).filter(x=>x.name);const catalog={destinations,hotels:(b.hotels||[]).map(x=>safeItem(x,"hotel")),safaris:(b.safaris||[]).map(x=>safeItem(x,"safari")),updatedAt:new Date().toISOString(),updatedBy:s.email};writeJSON(CATALOG,catalog);return json(res,200,{ok:true,catalog});}catch(e){return json(res,400,{ok:false,error:e.message});}
  if(p==="/api/admin/enquiries"&&req.method==="GET"){if(!requireAdmin(req,res))return;return json(res,200,readEnquiries());}
  if(p==="/api/admin/enquiry"&&req.method==="PUT")try{const s=adminWrite(req,res);if(!s)return;const b=await body(req),items=readEnquiries(),i=items.findIndex(x=>x.id===b.id);if(i<0)return json(res,404,{ok:false,error:"Enquiry not found."});items[i]={...items[i],status:["new","contacted","quoted","booked","closed"].includes(b.status)?b.status:items[i].status||"new",destination:clean(b.destination,100),travelDates:clean(b.travelDates,80),response:clean(b.response,3000),notes:clean(b.notes,3000),updatedAt:new Date().toISOString(),updatedBy:s.email};writeJSON(ENQUIRIES,items);return json(res,200,{ok:true,enquiry:items[i]});}catch(e){return json(res,400,{ok:false,error:e.message});}
  if(p==="/api/admin/bookings"&&req.method==="GET"){if(!requireAdmin(req,res))return;return json(res,200,readJSON(BOOKINGS,[]));}
  if(p==="/api/admin/booking"&&req.method==="PUT")try{const s=adminWrite(req,res);if(!s)return;const b=await body(req),items=readJSON(BOOKINGS,[]),record={id:clean(b.id,80)||crypto.randomUUID(),guestName:clean(b.guestName,100),email:clean(b.email,120),destination:clean(b.destination,100),property:clean(b.property,120),travelDates:clean(b.travelDates,80),guests:Math.max(1,Number(b.guests)||1),value:Math.max(0,Number(b.value)||0),currency:clean(b.currency,6)||"USD",source:clean(b.source,40)||"Direct",affiliateReference:clean(b.affiliateReference,160),enquiryId:clean(b.enquiryId,80),status:["provisional","confirmed","completed","cancelled"].includes(b.status)?b.status:"confirmed",notes:clean(b.notes,2000),updatedAt:new Date().toISOString(),updatedBy:s.email};if(!record.guestName||!record.destination)throw Error("Guest name and destination are required.");const i=items.findIndex(x=>x.id===record.id);if(i<0){record.createdAt=new Date().toISOString();items.unshift(record);}else items[i]={...items[i],...record};writeJSON(BOOKINGS,items);return json(res,200,{ok:true,booking:record});}catch(e){return json(res,400,{ok:false,error:e.message});}
  if(p==="/api/affiliate-click"&&req.method==="POST")try{const b=await body(req),click={id:crypto.randomUUID(),createdAt:new Date().toISOString(),propertyId:clean(b.propertyId,80),destination:clean(b.destination,100),url:clean(b.url,500)};fs.mkdirSync(DATA,{recursive:true});fs.appendFileSync(CLICKS,`${JSON.stringify(click)}\n`);return json(res,201,{ok:true});}catch{return json(res,400,{ok:false});}
  if(p==="/api/enquiries"&&req.method==="POST")try{const b=await body(req),q={id:crypto.randomUUID(),createdAt:new Date().toISOString(),name:clean(b.name,80),email:clean(b.email,120).toLowerCase(),phone:clean(b.phone,40),destination:clean(b.destination,60),travelDates:clean(b.travelDates,40),travelStyle:clean(b.travelStyle,40),message:clean(b.message,1000),status:"new",response:"",notes:""};if(!q.name||!email(q.email))return json(res,400,{ok:false,error:"Name and a valid email are required."});const items=readEnquiries();items.unshift(q);writeJSON(ENQUIRIES,items);return json(res,201,{ok:true,id:q.id});}catch{return json(res,500,{ok:false,error:"Could not save your enquiry."});}
  if(req.method!=="GET"&&req.method!=="HEAD")return json(res,405,{ok:false,error:"Method not allowed"});
  let pathname=p==="/"?"/index.html":p==="/admin"?"/admin.html":decodeURIComponent(p),file=path.resolve(ROOT,`.${pathname}`);if(!file.startsWith(`${ROOT}${path.sep}`))return json(res,403,{ok:false,error:"Forbidden"});if(!fs.existsSync(file)||!fs.statSync(file).isFile())file=path.join(ROOT,"index.html");const ext=path.extname(file).toLowerCase();res.writeHead(200,{"Content-Type":MIME[ext]||"application/octet-stream","Cache-Control":ext===".html"?"no-cache":"public, max-age=604800","X-Content-Type-Options":"nosniff","X-Frame-Options":"DENY","Referrer-Policy":"strict-origin-when-cross-origin"});if(req.method==="HEAD")return res.end();fs.createReadStream(file).pipe(res);
});
server.listen(PORT,()=>console.log(`EastAfricaExplore running at http://localhost:${PORT}`));
